# Generated by Django 6.0.6 on 2026-07-09 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del edificio')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo de edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=150, verbose_name='Nombre completo del propietario')),
                ('costo_departamento', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo del departamento')),
                ('num_cuartos', models.IntegerField(verbose_name='Número de cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_departamentos', to='inmobiliaria.edificio')),
            ],
        ),
    ]
